apiVersion: apps/v1
kind: Statefulset
metadata:
  namespace: kvstore-k8s
  name: kvstore-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kvstore
  template:
    metadata:
      labels:
        app: kvstore
    spec:
      containers:
      - name: kvstore
        image: ermiashabtegabr/kvstore:latest
        ports:
        - containerPort: 8080
