server: v1
kind: Service
metadata:
  namespace: kvstore-k8s
  name: kvstore-service
spec:
  clusterIP: None
  selector:
    app: kvstore
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
